### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Taketai** [Taketai/furima-35685#9]
フリマアプリのURL: 
https://furima-35685.herokuapp.com/

Basic認証のIDとパスワード: 
ID:take
PASS:0720

出品者用のメールアドレスとパスワード:
MAIL: rurukoro2010@gmail.com
PASS: hoge1111

購入者用のメールアドレスとパスワード	
MAIL: rurukoro2100@gmail.com
PASS: hoge2222

**Comment by snkw-works** [comment]
@Taketai さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [x] **本番環境で投稿した商品画像が、S3に保存されるよう修正しましょう**
現状、S3に保存されておりません。

- [x] **ログイン状態の出品者以外のユーザーのみ、必要な情報を適切に入力すると、商品の購入ができるよう修正しましょう**
現状、以下のような正しい情報を入力しても「Token can't be blank」というエラーになってしまい、購入が完了できない状態です。
<img width="1430" alt="スクリーンショット 2021-05-31 9 49 45" src="https://user-images.githubusercontent.com/54050089/120125943-95d75e80-c1f5-11eb-8a20-28817eddd124.png">

※購入機能と購入後に関する項目に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Taketai** [comment]
ご指摘ありがとうございましたm(_ _)m
上記の件　修正しましたので確認をお願いします！！

追記：
購入機能が上手くできているかを確認するために
「てすと」という商品を作っていますのでよろしくお願いします。

**Comment by snkw-works** [comment]
@Taketai さん、ご提出ありがとうございます‼︎
修正が確認でき、問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/120145696-ea430400-c21e-11eb-9bb7-880e364eae24.png)

**Comment by Taketai** [comment]
確認ありがとうございます‼️
最近LGTMという言葉をいただくことが大変うれしくなっております(´ω｀)
更なる精進を目指し追加実装を楽しみたいと思います！
